### ISSUE TITLE
recent links

### ISSUE THREAD

**Issue by ifVilius** [Danielku15/BetterStartPage#16]
in Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

recent links dont work

**Comment by THammond9** [comment]
I have this problem as well.

**Comment by THammond9** [comment]
I have traced this problem to `private void OpenProject(Project project)` in file ProjectGroupsViewModel.cs not being called when the project is clicked in the MRUListBox. I am not yet sure why this is happening though. Thought I would let you know in case it is more useful to you than me. Perhaps it is because the MRUListBox is referencing version 12 and not 14? It seems that in VS 2015 they moved the save location for the MRUListBox [(See this StackOverflow link)](http://stackoverflow.com/questions/33943943/clear-recent-projects-list-in-visual-studio-2015/33945037#33945037)

**Comment by Danielku15** [comment]
The MRUListBox of Visual Studio does not call my own ViewModel so this is correct. It should be a fully standalone control that comes with the original page. I wasn't able to find out exactly what happens there. Since the list is displayed also the commands should work.

**Comment by THammond9** [comment]
I am pretty sure that this issue is caused because the MRUListBox is version 12 (VS 2013) when it should be using version 14 (VS 2015). I changed the references in StartPage.xaml to version 14, then deleted any issues (don't really know how to fix them), ran the extension and the MRUListBox works. Just to verify that the deleted code did not change anything, I changed all DLL versions back (but did not restore the code deleted above) and when I ran the extension the MRUListBox no longer works.

**Comment by THammond9** [comment]
I believe that I have fixed this issue in my fork (it is the only commit). I strongly suspect that this change will break the MRUListBox for VS2013 but I do not have it installed on my PC so I cannot confirm. Not sure how to go about applying this fix so that BetterStartPage works on all versions of visual studio since VS2012.

**Comment by wilsade** [comment]
Hi there.
I tried THammond9 fork in VS 2015 and the recent projects works for me too.

I'd like to contribute to one thing:
**The behavior of the checkBox "Close page after project load" changed in VS2015**.
In VS2015, the text is: "Keep page open after project loads"
The binding also needs to be fixed.

Please, consider change it from:
```
Content="Close page after project load" 
IsChecked="{Binding ClosePageOnOpenProject, Mode=TwoWay}" 
```
to

```
Content="Keep page open after project loads" 
IsChecked="{Binding KeepPageOpenAfterOpenProject, Mode=TwoWay}" 
```

Please let me know if it works for you.
If it does, can you please submit a fix?

Thanks,
Wilsade

**Comment by Danielku15** [comment]
With the latest rework all problems should be fixed. I reuse the original start page now which should ensure all changes done by Microsoft are automatically included in BetterStartPage
