### ISSUE TITLE
ArgumentException after update to 1.14

### ISSUE THREAD

**Issue by mesal** [Danielku15/BetterStartPage#27]
After updating to version 1.14 start page refuse to load with the following exception:

> **Content Load Error**
> System.ArgumentException loading "C:\Program fIles (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\xfqj5z4g.nxa\StartPage.xaml":
> 
> Cannot use absolute URI.

Seems redefining the start page in the Environment > Startup fixes the issue.

**Comment by Danielku15** [comment]
Yes, this is quite an annoying issue of Visual Studio. Some times, due to (for me) unknown reason an update of the extension also means that either the installation folder changes or that it resets the start page to the default startpage. I am sure if there is a way to control this. 

Configuring again the startpage tells VS where to find the new XAML which defines the startpage.
