### ISSUE TITLE
When using multiple columns, grow from top to bottom instead of left to right

### ISSUE THREAD

**Issue by stijnherreman** [Danielku15/BetterStartPage#35]
I prefer sorting my solutions in lexicographical order. When using multiple columns, sorting becomes a bit of a hassle.

Consider solutions A, B, C, D and E. When using one column, you get:

column 1 |
-- |
A |
B |
C |
D |
E |

When switching to two columns, you get:

column 1 | column 2
-- | --
A | B
C | D
E | 

I'd rather have it appear like this:

column 1 | column 2
-- | --
A | D
B | E
C | 

Of course I can still sort them to appear like that, but when you add a new solution that is to appear somewhere in the middle of the list, it would cause a mess in the sorting again.

Is it possible to add an option, to make the list grow from top to bottom instead of left to right?

**Comment by GabrielBBF** [comment]
@Danielku15  Is this extension still being maintained? Would love to have this option.

**Comment by Danielku15** [comment]
> Is it possible to add an option, to make the list grow from top to bottom instead of left to right?

I would need to check if the panel I'm currently using would support this. Otherwise I'd need to create an own layout panel. But technically it should be doable. 


> @Danielku15 Is this extension still being maintained? Would love to have this option.
Not very actively. I lately have not much time to develop anything in my spare time. Of course I'm happy to accept any PRs that add new functionality or fixes.
